### ISSUE TITLE
Can you give me a contact number?

### ISSUE THREAD

**Issue by Choicc** [xuehaijun88/xuehaijun#1]
你好,看到你也在整合源,想和你交流一下,能给个联系方式吗? @xuehaijun88 看到希望你能回复我一下。

**Comment by xuehaijun88** [comment]
我的微信18362105821 ------------------ 原始邮件 ------------------
发件人: "Choicc"<notifications@github.com>
发送时间: 2019年7月9日(星期二) 晚上7:28
收件人: "xuehaijun88/xuehaijun"<xuehaijun@noreply.github.com>;
抄送: "iplay"<275485410@qq.com>;"Mention"<mention@noreply.github.com>;
主题: [xuehaijun88/xuehaijun] Can you give me a contact number? (#1)



你好,看到你也在整合源,想和你交流一下,能给个联系方式吗? @xuehaijun88
 
&mdash;
